name: ptxprint # you probably want to 'snapcraft register <name>'
version: '20200520' # just for humans, typically '1.2+git' or '1.3.2'
summary: ptxprint
architectures: [ all ]
base: core18
description: |
   GUI frontend to XeTex typesetting macros for USFM

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  ptxprint:
    command: /usr/local/bin/ptxprint

parts:
  ptxprint:
    plugin: python
    python-version: python3
    python-packages:
        - pip
    build-packages: 
        - python3-pip
        - python3-setuptools
    stage-packages:
        - python3-gi
        - gobject-introspection
        - gir1.2-gtk-3.0
        - libgtk-3-0
        - gir1.2-gtksource-3.0
        - python3-cairo
        - python3-regex
        - python3-img2pdf
        - texlive-xetex
        - fonts-sil-charis
    source-subdir: python
